import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships one English-only material-agnostic multilayer interface", async () => {
  const files = await Promise.all(["index.html", "src/App.tsx", "src/multilayer-app.ts", "src/model-help.ts", "src/scientific-core.ts", "src/dielectric-models.ts"].map((name) => readFile(new URL(`../${name}`, import.meta.url), "utf8")));
  const main = await readFile(new URL("../src/main.tsx", import.meta.url), "utf8");
  const vite = await readFile(new URL("../vite.config.ts", import.meta.url), "utf8");
  const styles = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
  const tokens = await readFile(new URL("../tokens.css", import.meta.url), "utf8");
  const combined = files.join("\n");
  assert.match(files[0], /<html lang="en">/);
  for (const metadata of ["theme-color", "canonical", "favicon.svg", "og:site_name", "og:url", "og:image:alt", "twitter:title", "twitter:description", "twitter:image:alt"]) {
    assert.match(files[0], new RegExp(metadata));
  }
  assert.match(files[0], /src="\/src\/main\.tsx"/);
  assert.match(main, /createRoot/);
  assert.match(files[1], /useEffect/);
  assert.match(vite, /base: "\/reflectometry\/"/);
  assert.doesNotMatch(files[1], /tool-heading|Capabilities and model scope/);
  assert.match(files[1], /href="#reflectometry-workspace"/);
  assert.match(files[1], /id="reflectometry-workspace"/);
  assert.match(files[1], /id="configuration-panel"/);
  assert.match(files[1], /id="results-panel"/);
  assert.match(files[1], /from "@headlessui\/react"/);
  assert.match(files[1], /from "@heroicons\/react\/24\/outline"/);
  assert.match(files[1], /<WorkflowSection[^>]+defaultOpen/);
  assert.match(files[1], /<DisclosurePanel[^>]+unmount=\{false\}/);
  assert.match(files[1], /<PopoverPanel/);
  assert.match(files[1], /<TabGroup/);
  for (const tab of ["Overview", "Spectra", "Optical constants"]) assert.match(files[1], new RegExp(`<Tab className="results-tab">${tab}<`));
  assert.equal((files[1].match(/<TabPanel className="results-tab-panel" unmount=\{false\}>/g) ?? []).length, 3);
  assert.match(files[1], /href="https:\/\/jorpago2\.github\.io\/"/);
  assert.match(files[1], /id="reset-example"/);
  assert.match(files[1], /id="saved-fit-file"/);
  assert.match(files[1], /R reference signal/);
  assert.match(files[1], /id="add-layer"/);
  assert.match(files[1], /id="substrate-editor"/);
  assert.match(files[1], /id="substrate-thickness"/);
  assert.match(files[1], /micrometres \(µm\)/);
  assert.match(files[1], /id="stack-diagram"/);
  assert.match(files[1], /LAYERS N,K/);
  for (const id of ["undo-button", "redo-button", "bootstrap-button", "cancel-operation", "print-report", "uncertainty-content", "solutions-content"]) assert.match(files[1], new RegExp(`id="${id}"`));
  for (const id of ["rt-chart", "residual-chart", "nk-chart"]) {
    assert.match(files[1], new RegExp(`canvasId="${id}"`));
  }
  assert.match(files[1], /data-reset-chart=\{canvasId\}/);
  assert.match(files[2], /Independent dielectric components/);
  assert.match(files[2], /function renderStackDiagram/);
  assert.match(files[2], /function markResultStale/);
  assert.match(files[2], /state\.resultStale/);
  assert.match(files[2], /Tauc–Lorentz oscillators/);
  assert.match(files[2], /Lorentz oscillators/);
  assert.match(files[2], /Brendel–Bormann/);
  assert.match(files[2], /Drude–Smith/);
  assert.match(files[2], /Effective-medium constituents/);
  assert.match(files[2], /Model guide/);
  assert.match(files[3], /Kramers–Kronig/);
  assert.match(files[2], /https:\/\/doi\.org\//);
  const modelSelector = files[2].match(/const MULTILAYER_MODEL_LABELS = \{([\s\S]*?)\n\};/)[1];
  assert.doesNotMatch(modelSelector, /\btl1\b|\btl2\b|tl-gaussian|drude-tl|MODEL_LABELS\.cody/);
  assert.match(files[2], /className = "parameter-help-button"/);
  assert.match(files[2], /function handleParameterHelp/);
  assert.match(files[2], /aria-expanded/);
  assert.match(styles, /\.parameter-help-popover\b/);
  assert.match(styles, /\.chart-tooltip\b/);
  assert.match(styles, /Hallmark · macrostructure: Workbench · genre: modern-minimal/);
  assert.match(styles, /@import url\("\.\.\/tokens\.css"\)/);
  assert.match(styles, /tailwindcss\/utilities\.css/);
  assert.match(styles, /@theme inline/);
  assert.doesNotMatch(styles, /tailwindcss\/preflight|@import\s+["']tailwindcss["']/);
  assert.match(files[1], /bg-ui-canvas/);
  assert.match(styles, /--plot-blue: var\(--color-plot-r\)/);
  assert.match(tokens, /--color-accent: oklch\(/);
  assert.match(tokens, /--font-display: "Space Grotesk"/);
  assert.doesNotMatch(styles, /:\s*#[0-9a-f]{3,8}\b|rgba?\(|100vw/i);
  assert.doesNotMatch(styles, /parameter-help-mark/);
  assert.match(files[2], /substrateThicknessNm: 1000 \* substrateThicknessUm/);
  assert.match(files[2], /parseSavedFit/);
  assert.match(files[2], /SAVED_FIT_SCHEMA/);
  assert.match(files[2], /function makeSubstrate/);
  for (const helper of ["renderChart", "niceTicks", "handleChartWheel", "handleChartKeydown", "resetChart"]) assert.match(files[2], new RegExp(`function ${helper}`));
  assert.match(files[2], /getBoundingClientRect\(\)/);
  assert.match(files[2], /context\.setTransform\(pixelWidth \/ width, 0, 0, pixelHeight \/ height/);
  assert.doesNotMatch(files[2], /Math\.min\(2, window\.devicePixelRatio/);
  assert.match(files[2], /parameter-link/);
  assert.match(files[4], /bootstrapFitUncertainty/);
  assert.match(files[2], /thicknessUm: Number\(elements\["substrate-thickness"\]\.value\)/);
  assert.match(files[2], /deterministic browser-generated example/);
  for (const selector of ["layer-actions", "component-selector", "layer-reference", "layer-flags", "parameter-header", "parameter-row"]) assert.match(styles, new RegExp(`\\.${selector}\\b`));
  assert.doesNotMatch(styles, /\.parameter-grid\b/);
  assert.doesNotMatch(styles, /\.tool-heading\b/);
  assert.match(styles, /overflow-x: clip/);
  assert.match(files[2], /initializeWorkspace\(\);/);
  assert.doesNotMatch(files[2], /loadSyntheticExample\(\);\s*$/);
  assert.doesNotMatch(combined, new RegExp(["single", "layer"].join("[- ]") + "|material " + "preset|included example", "i"));
  assert.doesNotMatch(combined, /\b(?:Cargar|Ajustar|Calibración|Muestra|Espesor|Índice|Parámetros|Reflectancia|Transmitancia)\b/i);
});
