import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships one English-only material-agnostic multilayer interface", async () => {
  const files = await Promise.all(["index.html", "multilayer.html", "multilayer-app.js", "model-help.js", "scientific-core.js", "dielectric-models.js"].map((name) => readFile(new URL(`../${name}`, import.meta.url), "utf8")));
  const styles = await readFile(new URL("../styles.css", import.meta.url), "utf8");
  const combined = files.join("\n");
  assert.match(files[0], /<html lang="en">/);
  assert.match(files[0], /url=multilayer\.html/);
  assert.match(files[1], /Build the stack/);
  assert.match(files[1], /id="reset-example"/);
  assert.match(files[1], /R reference signal/);
  assert.match(files[1], /id="add-layer"/);
  assert.match(files[1], /id="substrate-extinction"/);
  assert.match(files[1], /id="substrate-thickness"/);
  assert.match(files[1], /micrometres \(µm\)/);
  assert.match(files[1], /id="stack-diagram"/);
  assert.match(files[1], /LAYERS N,K/);
  assert.match(files[2], /Independent dielectric components/);
  assert.match(files[2], /function renderStackDiagram/);
  assert.match(files[2], /Tauc–Lorentz oscillators/);
  assert.match(files[2], /Lorentz oscillators/);
  assert.match(files[2], /Brendel–Bormann/);
  assert.match(files[2], /Drude–Smith/);
  assert.match(files[2], /Effective-medium constituents/);
  assert.match(files[2], /Model guide/);
  assert.match(files[3], /Kramers–Kronig/);
  assert.match(files[2], /https:\/\/doi\.org\//);
  const modelSelector = files[2].match(/const MULTILAYER_MODEL_LABELS = \{([\s\S]*?)\n\};/)[1];
  assert.doesNotMatch(modelSelector, /\btl1\b|\btl2\b|tl-gaussian|drude-tl|MODEL_LABELS\.cody/);
  assert.match(files[2], /className = "parameter-help-button"/);
  assert.match(files[2], /function handleParameterHelp/);
  assert.match(files[2], /aria-expanded/);
  assert.match(styles, /\.parameter-help-popover\b/);
  assert.doesNotMatch(styles, /parameter-help-mark/);
  assert.match(files[2], /substrateThicknessNm: 1000 \* substrateThicknessUm/);
  assert.match(files[2], /thicknessUm: Number\(elements\["substrate-thickness"\]\.value\)/);
  assert.match(files[2], /deterministic browser-generated example/);
  for (const selector of ["layer-actions", "component-selector", "layer-reference", "layer-flags", "parameter-header", "parameter-row"]) assert.match(styles, new RegExp(`\\.${selector}\\b`));
  assert.doesNotMatch(styles, /\.parameter-grid\b/);
  assert.match(styles, /\.hero h1 \{ font-size: clamp\(38px, 11vw, 42px\); \}/);
  assert.doesNotMatch(combined, new RegExp(["single", "layer"].join("[- ]") + "|material " + "preset|included example", "i"));
  assert.doesNotMatch(combined, /\b(?:Cargar|Ajustar|Calibración|Muestra|Espesor|Índice|Parámetros|Reflectancia|Transmitancia)\b/i);
});
